export type KnowledgeTerm = {
  slug: string;
  zh: string;
  en: string;
  abbr?: string;
  category: string;
  summary: string;
  definitionEn: string;
  why: string;
  example: string;
  formula?: string;
  fact: string;
  visual: 'curve' | 'balance' | 'nodes' | 'steps' | 'cashflow' | 'yield';
  related: string[];
};

export const knowledgeCategories = [
  '金钱与个人财务', '投资基础', '市场与产品', '财务报表',
  '公司金融与估值', '宏观经济', '组合与风险', '全球与衍生品',
] as const;

export const knowledgeTerms: KnowledgeTerm[] = [
  {
    slug: 'compound-interest', zh: '复利', en: 'Compound Interest', category: '金钱与个人财务', visual: 'curve',
    summary: '收益加入本金后，在下一期继续产生收益，时间因此成为增长的重要变量。',
    definitionEn: 'Interest calculated on both the original principal and the accumulated interest from earlier periods.',
    why: '它解释了长期储蓄为什么会加速增长，也解释了高息债务为什么会越来越难偿还。',
    example: '1 万元按 6% 年复利增长 20 年，约为 3.21 万元。', formula: '终值 FV = 本金 PV × (1 + r)ⁿ',
    fact: '“爱因斯坦称复利为世界第八大奇迹”的说法广为流传，但没有可靠的一手出处。',
    related: ['time-value', 'inflation', 'dollar-cost-averaging'],
  },
  {
    slug: 'time-value', zh: '货币时间价值', en: 'Time Value of Money', abbr: 'TVM', category: '金钱与个人财务', visual: 'cashflow',
    summary: '今天的一元钱通常比未来的一元钱更有价值，因为它现在就能被使用或投资。',
    definitionEn: 'The principle that money available today is worth more than the same amount in the future because of its earning capacity.',
    why: '贷款、债券、养老金、估值和投资决策，几乎都需要把不同时间点的金额放到同一把尺子上。',
    example: '若年利率为 5%，一年后的 105 元与今天的 100 元大致等价。', formula: '现值 PV = 未来金额 FV ÷ (1 + r)ⁿ',
    fact: '折现不是唱衰未来，而是校正等待时间、机会成本和风险。',
    related: ['compound-interest', 'present-value', 'npv'],
  },
  {
    slug: 'emergency-fund', zh: '应急金', en: 'Emergency Fund', category: '金钱与个人财务', visual: 'steps',
    summary: '专门用于失业、疾病或紧急维修等意外支出的高流动性资金。',
    definitionEn: 'Cash reserves set aside to cover unexpected expenses or a temporary loss of income.',
    why: '它能避免在市场低点卖出长期资产，或用高息借款支付突发开支。',
    example: '收入稳定者可从 3—6 个月必要支出起步，收入波动大者通常需要更厚的安全垫。', formula: '应急金目标 = 月必要支出 × 覆盖月数',
    fact: '应急金的首要目标是安全与可用，不是追求最高收益。',
    related: ['liquidity', 'debt-to-income', 'insurance'],
  },
  {
    slug: 'debt-to-income', zh: '债务收入比', en: 'Debt-to-Income Ratio', abbr: 'DTI', category: '金钱与个人财务', visual: 'balance',
    summary: '每月债务偿付额占月收入的比例，用来观察还款压力。',
    definitionEn: 'The percentage of gross monthly income used to pay recurring debt obligations.',
    why: '相同债务金额对不同收入家庭的压力完全不同，DTI 能提供更可比的衡量方式。',
    example: '月收入 2 万元、月还款 6000 元，DTI 为 30%。', formula: 'DTI = 月债务偿付额 ÷ 月收入 × 100%',
    fact: '贷款机构常用 DTI 评估偿付能力，但家庭还要考虑收入稳定性与抚养责任。',
    related: ['emergency-fund', 'amortization', 'insurance'],
  },
  {
    slug: 'amortization', zh: '摊还', en: 'Amortization', category: '金钱与个人财务', visual: 'steps',
    summary: '按照计划分期偿还贷款本金与利息，使余额逐步下降。',
    definitionEn: 'The gradual repayment of a loan through scheduled payments of principal and interest.',
    why: '它能揭示“月供相同”背后每期本金与利息构成如何变化。',
    example: '等额本息房贷早期月供中利息占比高，后期本金占比逐渐提高。',
    fact: '缩短期限通常能显著减少总利息，但会提高每月现金流压力。',
    related: ['debt-to-income', 'interest-rate', 'time-value'],
  },
  {
    slug: 'insurance', zh: '保险', en: 'Insurance', category: '金钱与个人财务', visual: 'nodes',
    summary: '用可承受的小额保费，把低概率但难以承受的大额损失转移给风险池。',
    definitionEn: 'A contract that transfers specified financial risks to an insurer in exchange for a premium.',
    why: '保险让家庭不必独自承担身故、重大疾病、责任事故等破坏性风险。',
    example: '先保障家庭收入支柱与大额医疗责任，再考虑可自行承担的小额损失。',
    fact: '“发生概率低”并不等于“不重要”，损失后果同样决定是否需要保障。',
    related: ['emergency-fund', 'risk-return', 'systemic-risk'],
  },

  {
    slug: 'risk-return', zh: '风险收益权衡', en: 'Risk–Return Trade-off', category: '投资基础', visual: 'balance',
    summary: '更高的预期收益通常要求承担更大的不确定性，不存在免费的高回报。',
    definitionEn: 'The relationship in which higher expected returns generally require accepting greater uncertainty or potential loss.',
    why: '它提醒投资者先识别收益来自承担什么风险，再比较宣传中的回报数字。',
    example: '短期要用的钱即使能承受账面波动，也不适合全部投入高波动股票。',
    fact: '风险不只等于价格波动，也包括永久损失、流动性枯竭和目标落空。',
    related: ['volatility', 'drawdown', 'margin-of-safety'],
  },
  {
    slug: 'diversification', zh: '分散投资', en: 'Diversification', category: '投资基础', visual: 'nodes',
    summary: '把资金配置到不同风险驱动因素的资产中，降低单一事件的冲击。',
    definitionEn: 'Spreading investments across assets whose risks are not perfectly aligned in order to reduce concentration risk.',
    why: '它不能消灭所有亏损，但可以降低某一公司、行业或地区失败造成的永久伤害。',
    example: '持有十家银行不一定充分分散，因为它们可能同受一个信贷周期影响。',
    fact: '真正的分散看底层风险来源，而不是账户里产品名称的数量。',
    related: ['correlation', 'asset-allocation', 'rebalancing'],
  },
  {
    slug: 'liquidity', zh: '流动性', en: 'Liquidity', category: '投资基础', visual: 'cashflow',
    summary: '资产快速、低成本并以合理价格转换成现金的能力。',
    definitionEn: 'The ease with which an asset can be converted into cash quickly without a material price concession.',
    why: '期限匹配依赖流动性；需要用钱时被迫折价卖出，可能把暂时波动变成永久损失。',
    example: '活期存款通常比房产更具流动性，因为房产成交需要时间并产生税费。',
    fact: '危机中“屏幕上有价格”不一定代表“按这个价格能成交”。',
    related: ['emergency-fund', 'bid-ask-spread', 'systemic-risk'],
  },
  {
    slug: 'volatility', zh: '波动率', en: 'Volatility', category: '投资基础', visual: 'curve',
    summary: '衡量价格或收益围绕平均水平波动幅度的统计指标。',
    definitionEn: 'A statistical measure of the dispersion of returns, commonly expressed as standard deviation.',
    why: '它帮助比较持有体验与短期不确定性，但不能覆盖欺诈、违约和永久损失等全部风险。',
    example: '两项资产平均收益相同，收益路径更剧烈的一项通常波动率更高。',
    fact: '低波动不等于安全；一些风险会长期潜伏，直到突然暴露。',
    related: ['risk-return', 'beta', 'sharpe-ratio'],
  },
  {
    slug: 'dollar-cost-averaging', zh: '定期定额投资', en: 'Dollar-Cost Averaging', abbr: 'DCA', category: '投资基础', visual: 'steps',
    summary: '按固定时间投入固定金额，在不同价格自动买入不同数量。',
    definitionEn: 'Investing equal amounts at regular intervals regardless of market price.',
    why: '它适合把持续收入转化为长期投资，也能减少一次性择时带来的心理压力。',
    example: '每月投入 1000 元，价格低时买得多、价格高时买得少。',
    fact: '定投降低择时压力，但不保证盈利，也不自动优于立即投入已有的一大笔现金。',
    related: ['compound-interest', 'rebalancing', 'asset-allocation'],
  },
  {
    slug: 'margin-of-safety', zh: '安全边际', en: 'Margin of Safety', category: '投资基础', visual: 'balance',
    summary: '在估计价值与支付价格之间预留缓冲，以承受预测误差和意外。',
    definitionEn: 'A buffer between estimated intrinsic value and the price paid, intended to protect against error and uncertainty.',
    why: '估值不可避免地依赖假设，安全边际承认“可能判断错”并给错误留下空间。',
    example: '估值区间中枢为 100 元，不代表 99 元就必然安全；还要看假设可靠性。',
    fact: '安全边际是风险管理思想，不是保证上涨的折扣标签。',
    related: ['present-value', 'dcf', 'risk-return'],
  },

  {
    slug: 'stock', zh: '股票', en: 'Stock / Equity', category: '市场与产品', visual: 'steps',
    summary: '代表企业剩余权益的所有权凭证，股东分享剩余收益并承担最后损失。',
    definitionEn: 'A security representing residual ownership in a company after its obligations are satisfied.',
    why: '理解股票是企业所有权，能把注意力从代码和短期价格拉回盈利、现金流与资本配置。',
    example: '股东长期回报通常来自盈利增长、分红与估值变化。',
    fact: '好公司和好股票不是同义词：买入价格会影响未来回报。',
    related: ['pe-ratio', 'free-cash-flow', 'roe'],
  },
  {
    slug: 'bond', zh: '债券', en: 'Bond', category: '市场与产品', visual: 'cashflow',
    summary: '发行人承诺按约支付利息并偿还本金的债务凭证。',
    definitionEn: 'A debt security under which an issuer promises specified interest and principal payments.',
    why: '债券把信用风险、利率风险和期限风险组合在一张合同里，是固定收益市场的基础。',
    example: '市场利率上升时，已发行的低票息债券通常需要降价才能与新债券竞争。',
    fact: '“固定收益”指合同现金流较明确，不代表市场价格不会波动。',
    related: ['yield-curve', 'duration', 'interest-rate'],
  },
  {
    slug: 'fund', zh: '基金', en: 'Investment Fund', category: '市场与产品', visual: 'nodes',
    summary: '集合多位投资者资金，按照约定策略投资一篮子资产的载体。',
    definitionEn: 'A pooled investment vehicle that holds a portfolio according to a stated mandate.',
    why: '基金能提供分散与专业管理，但最终风险取决于底层资产、策略和费用。',
    example: '同为“稳健”基金，底层可能分别是短债和高股息股票，风险完全不同。',
    fact: '挑基金先看持有什么，再看费用和策略，历史排名应放在后面。',
    related: ['etf', 'diversification', 'expense-ratio'],
  },
  {
    slug: 'etf', zh: '交易型开放式指数基金', en: 'Exchange-Traded Fund', abbr: 'ETF', category: '市场与产品', visual: 'nodes',
    summary: '可在交易所像股票一样买卖、通常追踪一篮子资产的基金。',
    definitionEn: 'A pooled fund whose shares trade on an exchange, often designed to track an index or asset basket.',
    why: 'ETF 把基金净值与市场交易结合起来，投资者要同时理解底层资产、折溢价和流动性。',
    example: '宽基指数 ETF 提供一篮子股票敞口，但仍会随整个市场下跌。',
    fact: '名称相似的 ETF 可能追踪不同指数，不能只凭简称判断持仓。',
    related: ['fund', 'bid-ask-spread', 'expense-ratio'],
  },
  {
    slug: 'yield-curve', zh: '收益率曲线', en: 'Yield Curve', category: '市场与产品', visual: 'yield',
    summary: '同类债务在不同到期期限上的收益率排列。',
    definitionEn: 'A curve plotting yields of comparable debt instruments across different maturities.',
    why: '它浓缩了市场对政策利率、通胀、增长和期限溢价的共同预期。',
    example: '正常曲线通常长期收益率高于短期；倒挂时短端可能高于长端。',
    fact: '曲线倒挂是重要信号，却不是精确预测衰退日期的时钟。',
    related: ['bond', 'duration', 'monetary-policy'],
  },
  {
    slug: 'duration', zh: '久期', en: 'Duration', category: '市场与产品', visual: 'yield',
    summary: '衡量债券现金流平均回收时间及其对利率变化敏感度的指标。',
    definitionEn: 'A measure of the timing of bond cash flows and the bond price sensitivity to interest-rate changes.',
    why: '到期日相同的债券也可能有不同利率风险，久期能更直接地比较价格敏感度。',
    example: '修正久期约 6 的债券，收益率上升 1 个百分点时，价格可能约下跌 6%。', formula: '价格变动约 ≈ −修正久期 × 收益率变动',
    fact: '久期是局部近似；利率变化很大时还要考虑凸性。',
    related: ['bond', 'yield-curve', 'interest-rate'],
  },

  {
    slug: 'balance-sheet', zh: '资产负债表', en: 'Balance Sheet', category: '财务报表', visual: 'balance',
    summary: '展示企业在某一时点拥有什么、欠什么，以及归股东所有的剩余权益。',
    definitionEn: 'A statement of a company’s assets, liabilities and shareholders’ equity at a specific date.',
    why: '它帮助判断资产质量、债务期限、流动性压力和资本结构。',
    example: '一家企业资产很多，但若短债集中到期且现金很少，仍可能面临偿债压力。', formula: '资产 = 负债 + 所有者权益',
    fact: '资产负债表像一张时点照片，利润表和现金流量表更像一段时间的视频。',
    related: ['income-statement', 'cash-flow-statement', 'current-ratio'],
  },
  {
    slug: 'income-statement', zh: '利润表', en: 'Income Statement', category: '财务报表', visual: 'steps',
    summary: '展示一段期间内收入如何逐层扣除成本、费用和税费并形成利润。',
    definitionEn: 'A statement showing revenue, expenses and profit over a reporting period.',
    why: '它揭示商业模式能否把销售转化为利润，以及成本结构是否可持续。',
    example: '营收增长 30%，若获客成本增长 60%，营业利润仍可能恶化。', formula: '净利润 = 收入 − 成本 − 费用 − 税费',
    fact: '一次性处置收益能推高净利润，却不代表主营业务改善。',
    related: ['balance-sheet', 'cash-flow-statement', 'gross-margin'],
  },
  {
    slug: 'cash-flow-statement', zh: '现金流量表', en: 'Cash Flow Statement', category: '财务报表', visual: 'cashflow',
    summary: '把现金变化拆成经营、投资与融资三类活动。',
    definitionEn: 'A statement explaining changes in cash through operating, investing and financing activities.',
    why: '利润包含应计项目，现金流量表能验证收入和利润是否真正转化为现金。',
    example: '利润增长但经营现金流下降，可能要检查应收账款、存货和收入确认。',
    fact: '盈利企业也可能因现金周转断裂而倒闭。',
    related: ['income-statement', 'free-cash-flow', 'balance-sheet'],
  },
  {
    slug: 'gross-margin', zh: '毛利率', en: 'Gross Margin', category: '财务报表', visual: 'steps',
    summary: '营业收入扣除直接营业成本后所剩比例，反映产品层面的经济性。',
    definitionEn: 'Revenue minus cost of goods sold, expressed as a percentage of revenue.',
    why: '毛利决定企业还有多少空间覆盖研发、销售、管理和资本成本。',
    example: '售价 100 元、直接成本 60 元，毛利率为 40%。', formula: '毛利率 = (收入 − 营业成本) ÷ 收入',
    fact: '跨行业直接比较毛利率常会误导，软件与零售的成本结构天然不同。',
    related: ['income-statement', 'roe', 'free-cash-flow'],
  },
  {
    slug: 'roe', zh: '净资产收益率', en: 'Return on Equity', abbr: 'ROE', category: '财务报表', visual: 'steps',
    summary: '企业用股东权益创造净利润的效率。',
    definitionEn: 'Net income earned relative to average shareholders’ equity.',
    why: 'ROE 可用于观察资本效率，但必须拆解利润率、周转效率和财务杠杆。',
    example: '两家公司 ROE 同为 20%，低负债公司的质量可能优于依赖高杠杆的公司。', formula: 'ROE = 净利润 ÷ 平均股东权益',
    fact: '大量举债回购股票会减少权益、推高 ROE，同时也提高财务风险。',
    related: ['leverage', 'balance-sheet', 'gross-margin'],
  },
  {
    slug: 'current-ratio', zh: '流动比率', en: 'Current Ratio', category: '财务报表', visual: 'balance',
    summary: '流动资产相对流动负债的比例，用于初步观察短期偿债能力。',
    definitionEn: 'Current assets divided by current liabilities, used as a basic liquidity indicator.',
    why: '它提示企业未来一年可用资源能否覆盖短期义务，但不能代替现金流分析。',
    example: '流动资产 200 万元、流动负债 100 万元，流动比率为 2。', formula: '流动比率 = 流动资产 ÷ 流动负债',
    fact: '库存滞销时，高流动比率也可能给出过度乐观的信号。',
    related: ['balance-sheet', 'liquidity', 'cash-flow-statement'],
  },

  {
    slug: 'free-cash-flow', zh: '自由现金流', en: 'Free Cash Flow', abbr: 'FCF', category: '公司金融与估值', visual: 'cashflow',
    summary: '经营产生的现金扣除维持和扩张所需资本支出后的余额。',
    definitionEn: 'Cash generated by operations after the capital expenditure needed to maintain and grow the business.',
    why: '它连接经营表现、资本投入与企业可以分配给资本提供者的真实现金。',
    example: '经营现金流 10 亿元、资本支出 4 亿元，简化自由现金流为 6 亿元。', formula: '简化 FCF = 经营现金流 − 资本支出',
    fact: '利润可受会计判断影响，现金最终必须真正进入或离开银行账户。',
    related: ['cash-flow-statement', 'dcf', 'wacc'],
  },
  {
    slug: 'present-value', zh: '现值', en: 'Present Value', abbr: 'PV', category: '公司金融与估值', visual: 'curve',
    summary: '未来现金流按要求回报率折算到今天的价值。',
    definitionEn: 'The value today of a future cash flow discounted at an appropriate required rate of return.',
    why: '现值使不同期限、风险和金额的机会可以在同一时间点比较。',
    example: '一年后的 105 元按 5% 折现，现值为 100 元。', formula: 'PV = FV ÷ (1 + r)ⁿ',
    fact: '折现率只变化一点，长期现金流的估值就可能发生很大变化。',
    related: ['time-value', 'dcf', 'npv'],
  },
  {
    slug: 'dcf', zh: '现金流折现', en: 'Discounted Cash Flow', abbr: 'DCF', category: '公司金融与估值', visual: 'curve',
    summary: '预测未来自由现金流并按风险折现，以估算资产或企业内在价值。',
    definitionEn: 'A valuation method that estimates value by discounting expected future cash flows.',
    why: 'DCF 强迫分析者明确增长、盈利、投入和资本成本假设，而不是只看一个估值倍数。',
    example: '企业价值由预测期现金流现值与终值现值共同组成。', formula: '企业价值 = Σ FCFₜ ÷ (1 + WACC)ᵗ + 终值现值',
    fact: 'DCF 的精确小数往往是假象，更有用的是情景区间与敏感性分析。',
    related: ['free-cash-flow', 'wacc', 'present-value'],
  },
  {
    slug: 'npv', zh: '净现值', en: 'Net Present Value', abbr: 'NPV', category: '公司金融与估值', visual: 'cashflow',
    summary: '未来现金流现值减去初始投入，用于判断项目是否创造价值。',
    definitionEn: 'The present value of future project cash flows minus the initial investment.',
    why: 'NPV 同时考虑现金流规模、发生时间和风险，是资本预算的核心原则。',
    example: '项目投入 100 万元，未来现金流现值为 118 万元，NPV 为 18 万元。', formula: 'NPV = Σ CFₜ ÷ (1 + r)ᵗ − 初始投资',
    fact: '回收期短不一定 NPV 高，因为回收期忽略了部分远期现金流与资金时间价值。',
    related: ['present-value', 'wacc', 'time-value'],
  },
  {
    slug: 'wacc', zh: '加权平均资本成本', en: 'Weighted Average Cost of Capital', abbr: 'WACC', category: '公司金融与估值', visual: 'balance',
    summary: '按照融资权重综合股东与债权人要求回报率的资本成本。',
    definitionEn: 'A company’s blended required return across equity and after-tax debt financing, weighted by market value.',
    why: '企业投资回报只有高于资金提供者要求的回报，才真正创造经济价值。',
    example: '权益占 70%、债务占 30% 时，不能只用债券利率作为整个企业的折现率。',
    fact: 'WACC 会随资本结构、市场利率和业务风险变化，不是一项永久常数。',
    related: ['dcf', 'npv', 'leverage'],
  },
  {
    slug: 'pe-ratio', zh: '市盈率', en: 'Price-to-Earnings Ratio', abbr: 'P/E', category: '公司金融与估值', visual: 'steps',
    summary: '股票价格相对每股收益的倍数，是常见但容易被误用的相对估值指标。',
    definitionEn: 'The market price per share divided by earnings per share.',
    why: '它能快速比较市场为每单位盈利支付多少，但必须结合增长、周期、会计质量和风险。',
    example: '股价 30 元、每股收益 2 元，静态市盈率为 15 倍。', formula: 'P/E = 每股价格 ÷ 每股收益',
    fact: '亏损企业的市盈率没有经济意义，周期顶点的低 P/E 也可能是陷阱。',
    related: ['stock', 'dcf', 'free-cash-flow'],
  },

  {
    slug: 'inflation', zh: '通货膨胀', en: 'Inflation', category: '宏观经济', visual: 'steps',
    summary: '一篮子商品与服务的整体价格水平持续上升，使货币购买力下降。',
    definitionEn: 'A sustained increase in the general price level of goods and services, reducing purchasing power.',
    why: '长期财务目标必须用实际购买力衡量，名义余额增加不一定代表真正变富。',
    example: '名义收益率 5%、通胀率 3% 时，实际购买力增长约 1.94%。', formula: '实际收益率 = (1 + 名义收益率) ÷ (1 + 通胀率) − 1',
    fact: '温和通胀与恶性通胀是完全不同的经济状态，不能只看“物价涨了”。',
    related: ['cpi', 'interest-rate', 'monetary-policy'],
  },
  {
    slug: 'gdp', zh: '国内生产总值', en: 'Gross Domestic Product', abbr: 'GDP', category: '宏观经济', visual: 'steps',
    summary: '一个经济体在一定期间内生产的最终商品和服务的市场价值。',
    definitionEn: 'The market value of final goods and services produced within an economy over a period.',
    why: 'GDP 是观察经济规模和增长的核心指标，但不能直接代表收入分配、生活质量或幸福感。',
    example: '支出法把经济活动拆为消费、投资、政府支出与净出口。', formula: 'GDP = C + I + G + (X − M)',
    fact: '二手商品交易通常不重复计入当期 GDP，但相关中介服务会计入。',
    related: ['inflation', 'unemployment', 'fiscal-policy'],
  },
  {
    slug: 'cpi', zh: '居民消费价格指数', en: 'Consumer Price Index', abbr: 'CPI', category: '宏观经济', visual: 'steps',
    summary: '追踪居民代表性消费篮子价格变化的指数。',
    definitionEn: 'An index measuring changes in prices paid by consumers for a representative basket of goods and services.',
    why: 'CPI 常用于衡量生活成本变化、调整合同和判断货币政策环境。',
    example: '总体 CPI 可被能源短期冲击影响，核心 CPI 常排除波动较大的食品与能源。',
    fact: '个人实际感受到的通胀可能与平均 CPI 不同，因为每个人的消费篮子不同。',
    related: ['inflation', 'monetary-policy', 'interest-rate'],
  },
  {
    slug: 'unemployment', zh: '失业率', en: 'Unemployment Rate', category: '宏观经济', visual: 'steps',
    summary: '劳动力中没有工作、正在寻找并可立即工作的人所占比例。',
    definitionEn: 'The share of the labor force without a job, available for work and actively seeking employment.',
    why: '它反映经济是否充分利用劳动力，但必须结合劳动参与率与就业质量阅读。',
    example: '停止找工作的人可能退出劳动力统计，使失业率下降却不代表就业真正改善。',
    fact: '失业率常是滞后指标，企业通常在需求变化一段时间后才调整用工。',
    related: ['gdp', 'monetary-policy', 'fiscal-policy'],
  },
  {
    slug: 'monetary-policy', zh: '货币政策', en: 'Monetary Policy', category: '宏观经济', visual: 'cashflow',
    summary: '中央银行通过政策利率、资产负债表和预期沟通影响金融条件与经济活动。',
    definitionEn: 'Actions by a central bank to influence interest rates, financial conditions, inflation and economic activity.',
    why: '它通过借贷成本、资产价格、汇率与信心影响需求，但传导存在时间差。',
    example: '加息通常提高新增贷款成本，并对利率敏感的住房与投资需求形成压力。',
    fact: '政策变化与经济效果之间常有“长且可变”的滞后。',
    related: ['interest-rate', 'inflation', 'yield-curve'],
  },
  {
    slug: 'fiscal-policy', zh: '财政政策', en: 'Fiscal Policy', category: '宏观经济', visual: 'cashflow',
    summary: '政府通过税收、支出和转移支付影响总需求、收入分配与资源配置。',
    definitionEn: 'Government decisions on taxation, spending and transfers that affect economic activity and distribution.',
    why: '财政政策可以直接改变居民与企业现金流，但也涉及债务可持续性和资源挤出。',
    example: '经济下行时，失业救济增加和税收减少会自动缓冲需求。',
    fact: '自动稳定器无需每次重新立法，也能随经济周期自动扩张或收缩。',
    related: ['gdp', 'unemployment', 'monetary-policy'],
  },

  {
    slug: 'asset-allocation', zh: '资产配置', en: 'Asset Allocation', category: '组合与风险', visual: 'nodes',
    summary: '根据目标、期限和风险预算决定股票、债券、现金等大类资产的比例。',
    definitionEn: 'The process of dividing a portfolio among asset classes according to goals, horizon and risk constraints.',
    why: '大类资产结构决定组合主要风险来源，通常比在同一类别内挑单一产品更重要。',
    example: '两年后的首付款和二十年后的养老金，应该使用不同的资产配置。',
    fact: '最优配置不是收益最高的组合，而是能承受、能坚持且能满足目标的组合。',
    related: ['diversification', 'rebalancing', 'correlation'],
  },
  {
    slug: 'rebalancing', zh: '再平衡', en: 'Portfolio Rebalancing', category: '组合与风险', visual: 'nodes',
    summary: '把偏离目标权重的投资组合恢复到预先设定的风险水平。',
    definitionEn: 'Restoring portfolio weights to their strategic targets after market movements cause drift.',
    why: '它把风险控制变成可执行规则，避免上涨后无意中持有过多高风险资产。',
    example: '目标股票 60%，上涨后变为 70%，可通过新增资金或卖出部分股票恢复。',
    fact: '再平衡不是预测赢家，而是在机械执行“控制风险、逆向调整”。',
    related: ['asset-allocation', 'diversification', 'dollar-cost-averaging'],
  },
  {
    slug: 'correlation', zh: '相关性', en: 'Correlation', category: '组合与风险', visual: 'nodes',
    summary: '衡量两个变量共同变动方向与程度，取值通常在 −1 到 +1 之间。',
    definitionEn: 'A statistic measuring the degree to which two variables move together, typically ranging from -1 to +1.',
    why: '组合风险不仅取决于每项资产多危险，也取决于它们是否在同一时间以相同方向波动。',
    example: '两只基金名称不同但都追踪同一指数，相关性可能接近 1。',
    fact: '危机时期许多风险资产相关性会同时上升，平时的分散效果可能减弱。',
    related: ['diversification', 'asset-allocation', 'beta'],
  },
  {
    slug: 'beta', zh: '贝塔系数', en: 'Beta', category: '组合与风险', visual: 'curve',
    summary: '衡量资产收益相对某个市场基准共同波动的敏感度。',
    definitionEn: 'A measure of an asset’s sensitivity to movements in a chosen market benchmark.',
    why: 'Beta 用于估计系统性市场暴露，但不描述公司特有风险、尾部风险或永久损失。',
    example: 'Beta 为 1.2 表示历史上市场变动 1% 时，该资产平均同向变动约 1.2%。',
    fact: 'Beta 依赖观察区间和基准选择，历史数值不是未来承诺。',
    related: ['volatility', 'correlation', 'sharpe-ratio'],
  },
  {
    slug: 'sharpe-ratio', zh: '夏普比率', en: 'Sharpe Ratio', category: '组合与风险', visual: 'balance',
    summary: '每承担一单位总波动所获得的超额收益。',
    definitionEn: 'Excess return over a risk-free rate divided by the standard deviation of returns.',
    why: '它使不同收益与波动水平的策略更可比，但仍不能充分描述尾部损失。',
    example: '两组合收益相同，波动更低的组合通常夏普比率更高。', formula: '夏普比率 = (组合收益 − 无风险收益) ÷ 收益波动率',
    fact: '样本短、收益分布偏斜或策略隐藏尾部风险时，夏普比率可能失真。',
    related: ['volatility', 'drawdown', 'beta'],
  },
  {
    slug: 'drawdown', zh: '最大回撤', en: 'Maximum Drawdown', abbr: 'MDD', category: '组合与风险', visual: 'curve',
    summary: '资产或组合从历史高点跌到随后低点的最大幅度。',
    definitionEn: 'The largest peak-to-trough decline over a specified observation period.',
    why: '回撤更接近投资者实际承受的亏损旅程，也能帮助评估是否会在低点被迫退出。',
    example: '净值从 100 跌到 70 后再恢复，最大回撤为 30%。', formula: '回撤 = (低点净值 − 先前高点) ÷ 先前高点',
    fact: '下跌 50% 后需要上涨 100% 才能回到原点。',
    related: ['risk-return', 'volatility', 'sharpe-ratio'],
  },

  {
    slug: 'interest-rate', zh: '利率', en: 'Interest Rate', category: '全球与衍生品', visual: 'yield',
    summary: '跨时间使用资金的价格，也是连接储蓄、借贷和资产估值的基础信号。',
    definitionEn: 'The price of borrowing money or the return earned for postponing consumption.',
    why: '利率变化会影响贷款月供、债券价格、企业投资、汇率和几乎所有长期资产估值。',
    example: '新债券收益率上升时，旧的低票息债券通常价格下降。',
    fact: '名义利率减去预期通胀，才更接近真实资金成本。',
    related: ['bond', 'inflation', 'monetary-policy'],
  },
  {
    slug: 'exchange-rate', zh: '汇率', en: 'Exchange Rate', category: '全球与衍生品', visual: 'balance',
    summary: '一种货币相对于另一种货币的价格。',
    definitionEn: 'The price of one currency expressed in units of another currency.',
    why: '海外投资、留学支出、进出口和跨国企业利润都同时受到汇率变化影响。',
    example: '海外资产上涨 8%，若对应外币相对本币贬值 5%，本币回报会被削弱。',
    fact: '汇率报价方向不同会让“升值”表述相反，阅读时先确认谁是基准货币。',
    related: ['hedging', 'interest-rate', 'asset-allocation'],
  },
  {
    slug: 'futures', zh: '期货', en: 'Futures Contract', category: '全球与衍生品', visual: 'cashflow',
    summary: '约定在未来日期按合约规则买卖标的资产的标准化合约。',
    definitionEn: 'A standardized exchange-traded contract to buy or sell an underlying asset at a future date.',
    why: '期货可用于价格风险管理，也因保证金机制和每日结算放大短期现金流压力。',
    example: '航空公司可用燃油期货降低未来油价上涨的不确定性。',
    fact: '期货回报不只取决于现货价格，还受期限结构、展期和保证金影响。',
    related: ['options', 'hedging', 'leverage'],
  },
  {
    slug: 'options', zh: '期权', en: 'Option', category: '全球与衍生品', visual: 'curve',
    summary: '赋予买方在约定期限内按约定价格买入或卖出标的资产的权利。',
    definitionEn: 'A contract giving the buyer the right, but not the obligation, to buy or sell an underlying asset at a specified price.',
    why: '期权能塑造非线性收益并转移特定风险，但定价和风险会受波动率与时间衰减影响。',
    example: '买入看跌期权类似为持仓购买一个有期限、带免赔额的价格保险。',
    fact: '期权买方有权利，卖方承担履约义务；卖方风险可能远超收到的权利金。',
    related: ['futures', 'hedging', 'volatility'],
  },
  {
    slug: 'hedging', zh: '风险对冲', en: 'Hedging', category: '全球与衍生品', visual: 'balance',
    summary: '建立相反或互补的风险敞口，以降低不利价格变化的影响。',
    definitionEn: 'Taking an offsetting or complementary position to reduce exposure to an adverse price movement.',
    why: '对冲的目标通常是降低不确定性，而不是让所有情景都赚得更多。',
    example: '未来有美元学费支出的人提前持有部分美元，是一种自然对冲。',
    fact: '有效对冲通常有成本，也可能放弃有利价格变化带来的部分收益。',
    related: ['exchange-rate', 'futures', 'options'],
  },
  {
    slug: 'leverage', zh: '杠杆', en: 'Financial Leverage', category: '全球与衍生品', visual: 'balance',
    summary: '使用借入资金或衍生工具放大对资产价格变化的敞口。',
    definitionEn: 'The use of debt or derivatives to magnify exposure, potential returns and potential losses.',
    why: '杠杆会放大收益与亏损，并可能因追加保证金把长期判断变成短期被迫卖出。',
    example: '自有资金 20 万元控制 100 万元资产，资产下跌 10% 会造成自有资金约 50% 的损失。',
    fact: '杠杆最大的危险往往不是方向判断错，而是正确之前先失去继续持有的能力。',
    related: ['futures', 'roe', 'systemic-risk'],
  },
  {
    slug: 'bid-ask-spread', zh: '买卖价差', en: 'Bid–Ask Spread', category: '全球与衍生品', visual: 'cashflow',
    summary: '市场最高买价与最低卖价之间的差额，是即时交易的重要隐性成本。',
    definitionEn: 'The difference between the highest price buyers offer and the lowest price sellers accept.',
    why: '频繁交易或买卖冷门资产时，价差会持续侵蚀回报，也反映市场流动性。',
    example: '买价 9.98 元、卖价 10.02 元，立即买入再卖出会先损失约 0.4%。',
    fact: '市场紧张时价差通常扩大，即使佣金不变，真实交易成本也会骤升。',
    related: ['liquidity', 'etf', 'systemic-risk'],
  },
  {
    slug: 'expense-ratio', zh: '基金费用率', en: 'Expense Ratio', category: '全球与衍生品', visual: 'steps',
    summary: '基金每年从资产中扣除的运营管理费用占平均资产的比例。',
    definitionEn: 'The annual operating expenses of a fund expressed as a percentage of average assets.',
    why: '费用是少数能在投资前确认的变量，长期差异会通过复利持续放大。',
    example: '同样的市场回报下，年费 1.5% 的产品长期终值会明显低于年费 0.2% 的产品。',
    fact: '费用通常已从基金净值中每日计提，不一定以单独账单出现。',
    related: ['fund', 'etf', 'compound-interest'],
  },
  {
    slug: 'systemic-risk', zh: '系统性风险', en: 'Systemic Risk', category: '全球与衍生品', visual: 'nodes',
    summary: '一个机构或市场的失灵通过相互连接、杠杆与信心冲击扩散到整个金融系统的风险。',
    definitionEn: 'The risk that disruption in one part of the financial system spreads and impairs the system as a whole.',
    why: '它解释了为什么单个机构看似理性的行为，聚合后可能产生挤兑、踩踏和流动性螺旋。',
    example: '抵押品价格下跌触发追加保证金，迫使多家机构同步卖出并进一步压低价格。',
    fact: '监管能降低系统风险，却不能保证单一投资盈利或消除所有危机。',
    related: ['leverage', 'liquidity', 'correlation'],
  },
];

export function getKnowledgeTerm(slug: string) {
  return knowledgeTerms.find((term) => term.slug === slug);
}
