import type { Course, CourseLesson } from './courses';

type LessonTuple = readonly [
  english: string,
  intuition: string,
  example: string,
  pitfall: string,
  exerciseHint: string,
];

export type LessonGuide = {
  english: string;
  plain: string;
  why: string;
  example: string;
  misconceptions: string[];
  exerciseHint: string;
};

const lessonNotes: Record<string, readonly LessonTuple[]> = {
  'finance-foundations': [
    ['Functions of Money — Money works as a medium of exchange, a unit of account, and a store of value.', '货币不是因为纸张本身值钱，而是因为大家相信它能被继续接受，并且有制度维持支付、清算和稀缺性。三项功能可能分开变弱：高通胀时仍能支付，却未必适合长期储值。', '假设一杯咖啡标价 30 元。人民币让买卖双方不必交换具体商品，也让不同商品能用同一单位比较；但如果物价一年翻倍，同样的 30 元就不再保留原来的购买力。', '把“国家发行”当成货币价值的全部来源，忽略可接受性、支付网络、供给约束与公众预期会共同变化。', '分别从支付、计价和储值三个角度回答，并给出一种功能失灵但另外两种仍在工作的情形。'],
    ['Time Value of Money — A yuan today is worth more than the same yuan received later because it can earn a return and provides liquidity now.', '不同时间的金额不能直接相加。今天的钱可以产生收益，也能处理眼前需要；未来的钱还带有通胀和无法按时收到的风险，所以必须先折算到同一时点。', '1 万元按年利率 4% 复利 3 年，终值约为 11,249 元。反过来，三年后的 11,249 元按 4% 折现，今天大约值 1 万元；两种计算只是方向相反。', '看到三年后多出 1,249 元就认为一定更富有，却没有扣除同期物价上涨，也没有确认 4% 是否确定可得。', '写出本金、利率、期数和计息频率；先算一年，再把下一年的本金更新，最后用公式复核。'],
    ['Compound Interest — Compounding means earning returns on both the original principal and previously earned returns.', '单利只让原始本金产生收益，复利则把已获得的收益也加入下一期本金。早期差距不明显，时间越长，增长越来越依赖“收益再产生收益”。', '1 万元年化 6%，按年复利 12 年约翻倍为 20,122 元；72 法则给出的估算是 72÷6=12 年。若每年把收益取走，余额不会形成同样的加速。', '把 72 法则当成精确公式，或用短期偶然获得的高收益率推算几十年，会把不确定性放大成夸张终值。', '先用 72 法则做心算，再用复利公式计算精确结果，并比较收益率下降 2 个百分点后的差异。'],
    ['Real Return — Real return measures how much purchasing power grows after accounting for inflation.', '账户余额是名义金额，真正影响生活的是它能购买多少商品和服务。实际收益把名义回报与通胀放在一起，适合比较跨年份的购买力。', '存款一年收益 5%，同期通胀 3%，精确实际收益为 1.05÷1.03−1≈1.94%，略低于简单相减的 2%。若还要缴税或付费，实际到手会更低。', '只用总体 CPI 代表自己的全部生活成本；住房、教育或医疗占比较高的人，个人通胀体验可能明显不同。', '统一同一期间，先算名义终值，再除以物价指数；最后加入税费，说明用的是官方还是个人消费篮子。'],
    ['Interest Rate — An interest rate is the price of using money over time and a discount rate for valuing future cash flows.', '利率一边决定借款和储蓄的价格，一边是资产估值的折现尺。其他条件相同时，市场利率上升，固定的未来现金流折到今天就更少，因此旧债券价格通常下降。', '一张一年后支付 100 元的零息债券：要求回报 4% 时今天约值 96.15 元；要求回报升到 6% 时只值约 94.34 元。现金流没变，折现价格变了。', '把央行政策利率与所有贷款、存款和债券收益率视为同一个数字；现实还叠加期限、信用、流动性与银行定价。', '画出储蓄者、借款人和资产价格三方关系，并用同一笔未来现金流比较两个折现率。'],
    ['Risk — Financial risk includes permanent loss, liquidity shortfall, purchasing-power erosion, and failure to meet a goal, not only price volatility.', '波动只是价格上下移动，风险还包括钱在需要时取不出、发行人违约、购买力下降和目标无法完成。是否危险取决于损失大小、发生概率与家庭能否承受。', '两年后必须支付 20 万元首付。即使某股票长期平均回报较高，若两年内可能下跌 35%，这笔钱就面临期限错配；对三十年后的养老资金，短期波动的含义又不同。', '把“过去波动小”当成安全，忽略某些产品可能因估值不及时或无法交易而看起来平稳。', '围绕一笔真实目标列出市场、信用、流动性、通胀和行为风险，再写明每种风险出现时的后果。'],
    ['Sources of Return — Total return combines income received and changes in the market value of the asset.', '收益需要追问“谁付的钱”。债券可能来自票息与价格变化，股票来自企业利润、分红和估值变化，房产还要扣除空置、维护和融资成本。', '100 元买入一项资产，一年收到 3 元现金并以 105 元卖出，总回报是 8%。其中收入回报 3%，资本利得 5%；若交易费用 1 元，净回报降为 7%。', '把价格上涨全部解释为基本面改善。短期价格也可能只是估值上升，未来若估值回落，之前的涨幅并非可持续收益来源。', '把回报拆成现金收入、经营增长、估值变化、汇率与费用五栏，逐项说明是否可持续。'],
    ['Financial Decision Framework — A sound decision links goals, time horizon, risk capacity, suitable instruments, and total cost.', '金融地图不是推荐某个产品，而是固定提问顺序：先确定目标和日期，再看可承受风险，最后才筛选工具并计算全部成本。顺序反过来就容易被热门产品牵着走。', '同样是 10 万元：半年后用于学费，应重视本金和流动性；二十年后用于养老，可以承受更长波动。金额相同，因为目标和期限不同，合适工具也不同。', '用一个“风险测评分数”替代完整判断。问卷反映的风险意愿可能随行情改变，而收入、期限与家庭责任决定的风险能力更加刚性。', '选一个真实目标，依次写下金额、日期、最低可接受结果、最大可承受损失、候选工具和全部费用。'],
  ],
  'personal-finance': [
    ['Net Worth — Net worth equals total assets minus total liabilities and provides a snapshot of financial position.', '目标要从“想存钱”改写为金额与日期，净资产则像某一天的财务照片。它不直接代表生活质量，却能显示资产是否足以覆盖负债以及长期方向是否改善。', '家庭有现金 8 万、基金 12 万、住房权益 40 万，同时有房贷 35 万和消费贷 3 万，净资产为 22 万。下月工资不是当天资产，未来支出也要单独规划。', '把自住房完整市值计入资产，却遗漏剩余房贷或高估难以快速变现的价值，导致对可用资金过度乐观。', '按保守可变现金额列资产，按当前应偿余额列负债；再给三个目标补上金额、日期和优先级。'],
    ['Bucket Budgeting — A bucket budget assigns income to essentials, goals, and discretionary spending before money is spent.', '预算不是惩罚消费，而是让重要事项先获得资源。分账户能把必要支出、目标储蓄和自由消费分开，减少月底才发现钱被无意识花掉的情况。', '月到手 12,000 元，可先设 6,000 元必要支出、3,000 元目标储蓄、3,000 元自由支出。若房租上涨，应明确从哪一栏调整，而不是让信用卡自动填补。', '机械套用 50/30/20 等比例，忽略高房租城市、抚养责任和收入波动，最终预算无法执行。', '用最近三个月流水算真实均值；先划必要支出和自动储蓄，再给自由消费保留可持续额度。'],
    ['Emergency Fund — An emergency fund is liquid money reserved for unexpected, necessary expenses or income interruption.', '应急金负责“防止被迫做坏决定”，不是追求最高收益。规模由必要支出、收入稳定性、家庭责任与保险等待期共同决定，存放位置要安全并能快速取用。', '月必要支出 8,000 元，稳定双职工家庭按 3—6 个月准备约 2.4万—4.8万元；收入高度波动且有抚养责任，可能需要 9—12 个月。', '把旅行、装修或每年保费等已知支出算作紧急事件；这些应另建目标账户，避免反复掏空安全垫。', '先从流水中剔除可暂停消费，得到必要支出；再按收入与家庭责任选择覆盖月数，并写明何时可以动用。'],
    ['Debt Repayment — The debt avalanche method pays the highest effective interest rate first, while the snowball method pays the smallest balance first.', '偿债顺序同时有数学和行为两面。高利率优先通常减少总利息，小余额优先更快获得完成感；不论哪种方法，都要先保证各笔债务最低还款不违约。', '三笔债务余额分别为 2 万@18%、8 万@6%、5千@0%。数学上先集中还 18% 的债务，同时支付另外两笔最低额；提前还款费可能改变排序。', '只比较宣传月费率或每期手续费，未把所有费用换成同一年的实际融资成本。', '列出余额、实际年化成本、最低还款、剩余期限和违约后果；先处理会迅速滚大的高成本债务。'],
    ['Cost of Credit — The annual percentage cost includes interest, mandatory fees, and the timing of repayments.', '信用成本不能只看“每月 0.5%”。分期本金不断偿还，却可能始终按初始本金收手续费，因此真实年化成本会明显高于简单乘以 12。', '借 12,000 元分 12 期，每月还本金 1,000 元并付 60 元手续费，总费用 720 元看似 6%，但平均占用本金远低于 12,000 元，实际资金成本更高。', '认为按时还最低还款就没有问题；循环利息、费用和信用记录影响可能让小额消费变成长期负担。', '画出每月实际收到与支付的现金流，用内部收益率计算年化资金成本，并阅读逾期和提前还款条款。'],
    ['Protection Gap — A protection gap is the difference between financial responsibilities after a loss and resources already available.', '保险适合转移“发生概率不一定高、但家庭无法自行承担”的损失。保额应从债务、抚养、收入替代和现有资产反推，而不是从销售套餐起步。', '家庭主要收入者离世后还需偿还 80 万房贷、准备 50 万教育金和 5 年生活费 60 万，已有可用资产 40 万，粗略保障缺口为 150 万。', '把储蓄型产品的展示收益当成保障是否充足的主要标准，反而忽略责任范围、免责、等待期和赔付条件。', '列出家庭无法承担的事件、对应金额和已有保障；逐条核对保险责任、免责、保额、期限与受益人。'],
    ['Rent versus Buy — The decision compares total housing costs, flexibility, and opportunity cost, not only rent versus mortgage payment.', '买房月供中有本金积累，也有利息成本；租房则保留迁移自由与首付款的其他用途。正确比较要把税费、维修、交易成本和机会成本都放进同一持有期。', '房价 300 万、首付 90 万，不仅要算贷款利息，还要算 90 万首付失去的投资机会、买卖税费与维护。若三年内可能换城市，较高交易成本尤其重要。', '把月租 6,000 元直接与月供 10,000 元比较，既没拆出月供中的本金，也遗漏首付和交易成本。', '选定预计居住年限，分别列租与买的现金流、可回收资产和迁移成本，再用多组房价与租金假设测试。'],
    ['Retirement Planning — Retirement planning estimates future spending in today’s purchasing power and builds a flexible funding plan.', '养老规划要先讨论退休后的生活，而不是先选产品。未来支出需考虑通胀、医疗、养老金和退休年限，长期数字误差很大，因此重点是持续投入与定期更新。', '今天每月需要 8,000 元生活费，按 2.5% 通胀，30 年后同等购买力约需 16,780 元。若收益、寿命或养老金变化，所需资产也会明显改变。', '看到一个巨大的退休目标后，靠提高收益率假设“解决缺口”；这只是让表格好看，并没有降低真实风险。', '用今天购买力列必要与可选支出，加入养老金和医疗情景；分别计算低收益、高通胀和长寿三种压力方案。'],
  ],
  'investment-products': [
    ['Cash and Money Market Funds — Cash offers immediate liquidity, while money market funds invest in short-term instruments and are not identical to bank deposits.', '现金的价值包括支付能力、缓冲和等待机会，但长期会受通胀侵蚀。货币基金通常流动性较高，却仍有底层资产、赎回和净值风险，不能与受保障存款混为一谈。', '三个月后必须支付 3 万元学费，这笔钱的首要任务是按时可用，不是争取多几个百分点收益。可将日常现金、应急金和短期目标分层存放。', '看到货币基金净值长期平稳，就认为它与活期存款完全相同，忽略赎回到账时间和极端市场下的流动性安排。', '核对用途日期、到账时间、存款保障或基金底层资产；为当天、数月内和长期资金分别选择位置。'],
    ['Structured Product — A structured product combines a deposit or bond component with a derivative payoff linked to market conditions.', '结构性产品的展示收益往往带条件。需要拆成保本或债权部分、挂钩标的、触发条件和到期支付公式，才能知道最好、一般与最坏结果。', '某产品写“年化 0.5%—6%”，只有指数期末落在指定区间才获得 6%，否则可能只有 0.5%。展示上限不能当作预期收益，更不能忽略提前退出限制。', '只看“存款”或“保本”字样，没有确认发行主体、保障范围、观察日与收益触发条件。', '把合同支付规则改写成三种情景表：触发什么、何时观察、到期拿回多少、能否提前退出。'],
    ['Bond and Credit Risk — A bond is a contractual claim on future payments, exposed to interest-rate, credit, inflation, and liquidity risk.', '买债券相当于把钱借给发行人。票息只是合同现金流，最终回报还受买入价格、到期收益率、是否违约和能否按合理价格卖出影响。', '面值 100 元、票息 3% 的债券，当市场对同类风险要求 5% 回报时会折价交易。若发行人信用恶化，即使利率不变，价格也可能下跌。', '认为“持有到期就没有风险”。前提是发行人不违约、期间不被迫卖出，而且通胀没有显著侵蚀回收本金的购买力。', '核对发行人、偿付顺序、到期日、收益率、久期和成交情况，再区分利率风险与信用风险。'],
    ['Equity Ownership — A share represents a residual claim on a company’s assets and future cash flows after other obligations are paid.', '股东拥有的是剩余权益：员工、供应商、税款和债权人先得到支付，剩下才属于股东。因此股票上行空间较大，经营失败时也更先承担损失。', '企业利润每股从 1 元增至 1.2 元，同时市盈率从 20 倍升到 25 倍，股价可从 20 元升到 30 元。涨幅一部分来自盈利增长，另一部分来自估值变贵。', '把好公司等同于好投资。即使业务优秀，若买入价格已经包含过度乐观增长，未来回报仍可能很差。', '用收入、利润、自由现金流、负债与估值五栏解释股价，区分企业变好与市场愿意付更高价格。'],
    ['Active and Index Funds — Active funds select securities, while index funds aim to track a specified benchmark before fees and tracking differences.', '基金把多个资产装进共同结构。主动基金依赖选股与配置能力，指数基金依赖指数规则；两者都要看底层暴露、费用、交易成本和是否偏离目标。', '两只同类基金费用分别为 0.2% 和 1.5%。若费用前长期回报相同，高费基金每年先少 1.3 个百分点，差距还会影响后续复利。', '把“指数”理解为被动且天然分散。有些指数集中在少数行业或按价格、主题规则编制，风险可能很集中。', '写下基金目标、基准、前十大持仓、行业集中度、全部费用与跟踪误差，再判断它在组合中的职责。'],
    ['ETF Mechanism — An ETF trades on an exchange while authorized participants help keep its market price close to net asset value.', 'ETF 同时有基金净值和市场成交价。申购赎回与套利机制通常让两者接近，但在底层市场关闭、流动性紧张或报价失真时，折溢价可能扩大。', '某 ETF 每份底层资产净值 10 元，市场价 10.20 元，溢价约 2%。如果追价买入，即使底层资产不变，溢价回落也会造成损失。', '只看屏幕成交量，不看买卖价差、底层资产流动性和交易时段，误以为所有 ETF 都同样容易退出。', '交易前查看实时估值、折溢价、买卖价差、成交额、跟踪误差和底层市场是否开放。'],
    ['Real Assets — Gold, commodities, and property have distinct return drivers, carrying costs, and liquidity characteristics.', '实物资产不是一个统一类别。黄金自身不产生经营现金流，商品期货受期限结构影响，出租房有租金但也有维护、空置、税费和融资成本。', '出租房年租金 12 万，不能直接用 12 万除以房价。还需扣除空置 1 万、维护 2 万、税费和贷款利息；黄金则更多依赖未来售价变化。', '用“抗通胀”三个字概括所有时期。资产对通胀的反应取决于供需、利率、买入估值和持有成本，并非稳定的一一对应。', '分别写出现金流、价格驱动、持有成本、融资方式和变现时间，不要只比较历史涨幅。'],
    ['Product Due Diligence — Due diligence verifies the provider, assets, custody, fees, liquidity, and economic source of returns.', '识别产品先问收益从哪里来，再核验主体与资金路径。无法解释盈利来源、承诺高收益低风险、催促转账或使用个人账户，都是需要立即停下的信号。', '某平台承诺月收益 3% 且“随时退出”。若无法提供受监管主体、托管账户、审计资产和真实借款人现金流，高回报很可能来自新资金而非经营收益。', '因为朋友已经盈利或平台可以正常提现，就认为模式安全；早期兑付本身不能证明底层资产真实。', '独立核验牌照、合同主体、收款账户、托管、底层资产、全部费用和退出规则；无法核验就不转账。'],
  ],
  'financial-statements': [
    ['Three Financial Statements — The income statement shows performance over a period, the balance sheet shows position at a date, and the cash-flow statement explains cash movements.', '三张表回答不同问题：赚了多少、拥有什么欠什么、现金怎样进出。它们通过净利润、留存收益、现金和非现金调整互相连接，不能只选最好看的一张。', '赊销 100 万会增加收入和应收账款，却暂时没有经营现金流入。客户付款时应收下降、现金上升，但不会再次确认收入。', '看到利润增长就认为现金一定增加，忽略赊销、存货、预付款和资本开支会占用大量资金。', '找出净利润如何进入现金流量表，再追踪期末现金如何与资产负债表现金余额一致。'],
    ['Gross Profit — Gross profit equals revenue minus the direct cost of goods or services sold.', '毛利展示每卖出一单位产品后，还剩多少资源覆盖销售、研发、管理、利息和税。毛利率变化要拆成售价、产品结构、原材料与产能利用率。', '收入 1 亿元、营业成本 6,000 万，毛利 4,000 万、毛利率 40%。若次年售价下降而原料上涨，收入可能增长但毛利率仍恶化。', '跨行业比较毛利率并直接判断优劣；软件、零售与制造的成本归类和资本需求完全不同。', '计算至少三年毛利率，结合销量、均价、产品结构和成本说明变动原因，并核对收入确认政策。'],
    ['Operating Profit — Operating profit measures profit from core operations before financing and some non-operating items.', '营业费用要区分维持当前业务与为未来增长投入。研发或获客短期压低利润，却可能创造未来能力；一次性处置收益则可能抬高利润但不可持续。', '公司主营营业利润 800 万，又出售房产获利 1,200 万，净利润看似很高。评估持续盈利时应把处置收益单列，并检查是否每年都有“非经常”项目。', '机械剔除所有费用来制造“调整后利润”，却没有判断股权激励、持续重组等项目是否实际上年年发生。', '从营业利润到税前利润逐项标记主营、融资和一次性项目，并用三年频率判断是否真的非经常。'],
    ['Asset Quality — Asset quality asks whether recorded receivables, inventory, goodwill, and fixed assets can generate or be converted into economic value.', '资产负债表上的金额不是保证可按原价变现。应收可能收不回、存货可能过时、商誉依赖收购业务表现，固定资产也可能闲置或需要继续投入。', '收入增长 10%，应收账款却增长 60%，应收天数从 45 天升到 70 天。这可能是放宽信用促进销售，也可能预示回款质量下降。', '资产越多就认为企业越安全；低效率资产会占用现金，减值还可能在未来集中暴露。', '比较应收和存货增速与收入增速，查看账龄、减值政策、周转天数和资本利用率。'],
    ['Solvency — Solvency evaluates whether operating cash and available liquidity can meet interest and principal payments when due.', '偿债风险不只看总负债，还要看什么时候到期、利率是否浮动、现金是否受限，以及经营利润能否覆盖利息。期限错配常比静态负债率更危险。', '企业有 10 亿元现金和 12 亿元一年内到期债务，看似差额不大；若其中 6 亿元现金受限，且经营现金流转弱，再融资压力就会明显增加。', '认为利息保障倍数高就没有风险，忽略到期本金、租赁义务、担保和现金流波动。', '制作未来三年到期表，对比可用现金、经营现金流、利息、资本开支与授信额度，并做收入下降压力测试。'],
    ['Operating Cash Flow — Operating cash flow reconciles accounting profit with non-cash items and changes in working capital.', '利润按权责发生制确认，现金流记录实际收付。经营现金流持续低于利润，可能因为增长占用营运资本，也可能因为收入质量或付款政策变化。', '净利润 1,000 万，但应收增加 600 万、存货增加 300 万，折旧加回 100 万，其他不变时经营现金流约 200 万。利润存在，现金被客户和库存占住。', '单季现金流为负就判断造假。季节性备货、集中回款和业务扩张都可能造成短期波动，需要结合多年与附注。', '从净利润出发，逐项解释折旧、应收、存货和应付变化；再计算多年现金转换率并寻找持续偏离。'],
    ['DuPont Analysis — Return on equity can be decomposed into profit margin, asset turnover, and financial leverage.', '同样的 ROE 可能来自高利润率、高周转或高杠杆，风险含义完全不同。杜邦分解的价值是提出问题，而不是把一个比率拆成三个比率就结束。', '甲公司利润率 20%、周转 0.5、权益乘数 2，ROE 约 20%；乙公司利润率 5%、周转 2、权益乘数 2，也约 20%，经营模式却截然不同。', '看到高 ROE 就判断经营优秀，忽略亏损、回购或高负债可能让账面权益很小，从而机械抬高比率。', '计算三项驱动并比较三年趋势；确认权益是否异常、利润是否有一次性项目，以及杠杆是否可持续。'],
    ['Financial Statement Investigation — A robust review combines trends, peer comparisons, accounting links, and questions about unusual changes.', '综合阅读像侦探工作：先找变化，再提出可能解释，然后用其他报表和附注验证。单一红旗不是定罪，多个相互关联的异常才更值得深入。', '收入增长、应收天数上升、经营现金流下降且退货准备减少，四个信号共同出现，比单看其中任何一个都更值得追问收入质量。', '先决定公司好坏，再从报表里挑支持观点的数据，形成确认偏误。', '固定使用十分钟检查表：审计意见、收入、利润、现金、应收存货、债务、关联交易、会计估计和股本变化。'],
  ],
  'corporate-valuation': [
    ['Economic Value Creation — A company creates economic value when return on invested capital exceeds its cost of capital.', '利润增长不等于创造价值。如果为了多赚 1 元利润投入了过多资本，而资本回报低于投资者要求的回报，规模扩大反而会破坏价值。', '项目投入 1,000 万，每年税后经营利润 80 万，ROIC 约 8%；若 WACC 为 10%，经济利润约为负 20 万。会计上盈利，经济上未覆盖资本成本。', '只看收入增速或净利润，不看增长需要的营运资本、设备与融资，容易奖励低质量扩张。', '估算投入资本、税后经营利润和资本成本；再判断新增增长的边际回报是否高于存量业务。'],
    ['Net Present Value — NPV equals the present value of future project cash flows minus the initial investment.', '净现值把项目所有增量现金流折到今天。NPV 为正表示在给定折现率和假设下，项目在补偿资本成本后仍有剩余价值。', '项目今天投入 100 万，未来三年各回收 40 万，按 8% 折现，三笔现金流现值合计约 103 万，NPV 约 3 万；若成本超支，结论可能转负。', '使用会计利润代替项目增量现金流，或把已经发生、无法收回的沉没成本继续算进决策。', '只列因接受项目而改变的现金流，写明时间点、税、营运资本和残值，再对销量与成本做敏感性分析。'],
    ['Capital Structure — Capital structure balances the benefits of debt financing against financial distress and loss of flexibility.', '债务要求固定支付，能在经营良好时放大股东回报，也会在收入下降时挤压现金。最优结构取决于现金流稳定性、资产抵押能力和未来融资需求。', '企业资产回报 12%，债务成本 5% 时，加杠杆可能提高 ROE；若衰退使资产回报降到 2%，利息仍需支付，股东损失会被同步放大。', '认为债务便宜就应尽量多借，忽略评级下降、再融资、契约限制和失去战略灵活性的成本。', '做正常与衰退情景，比较利息、到期本金、契约余量和可用现金；说明为何这种业务能承受该杠杆。'],
    ['Weighted Average Cost of Capital — WACC is the blended required return of debt and equity capital used to discount operating cash flows.', 'WACC 是资本提供者要求的综合回报。权益风险更高，要求回报通常高于债务；债务利息可能有税盾，但权重要尽量反映市场价值而非历史账面值。', '公司权益市场价值 70、债务 30，权益成本 12%、税后债务成本 4%，WACC=70%×12%+30%×4%=9.6%。', '用公司整体 WACC 折现风险完全不同的新项目；高风险项目会因此被高估，低风险项目可能被错杀。', '无风险利率、风险溢价与现金流必须使用同一币种，资本权重应采用市场价值，并按业务风险调整折现率。'],
    ['Free Cash Flow to the Firm — FCFF is cash generated by operations after taxes and reinvestment, available to all capital providers.', '自由现金流从经营利润出发，加回非现金费用，再扣除维持与增长所需的资本开支和营运资本。增长越快，短期占用现金可能越多。', '税后经营利润 1,000 万，加折旧 200 万，资本开支 350 万，营运资本增加 150 万，FCFF 为 700 万。若只看利润会高估可分配现金。', '把所有资本开支都视为坏事。高回报的增长投资会压低当期现金，却可能增加未来价值，关键在投入回报。', '从 EBIT 到 NOPAT，再依次处理折旧、资本开支和营运资本；核对增长假设需要多少再投资。'],
    ['Discounted Cash Flow — DCF values a business by discounting forecast free cash flows and a terminal value to the present.', 'DCF 的价值是让假设透明。预测期解释企业如何从当前经营走向成熟，终值代表更远期现金流；折现率把时间和风险转换成今天的价值。', '预测现金流现值 40 亿元、终值现值 60 亿元，企业价值 100 亿元。若终值占 60%，说明结论很依赖远期增长和折现率，应重点做敏感性。', '把模型做得很复杂就认为更准确。小数点很多不代表假设可靠，尤其当终值和利润率缺少经济解释时。', '建立悲观、基准、乐观三情景；检查终值占比、隐含成熟利润率和永续增长是否符合长期经济约束。'],
    ['Relative Valuation — Valuation multiples compare price with earnings, sales, book value, or cash flow among genuinely comparable businesses.', '倍数是被压缩的估值模型。市盈率差异往往隐含增长、风险、资本回报和会计质量差异；只有业务结构与会计定义可比，比较才有意义。', '甲公司 PE 15 倍、乙公司 25 倍，不能直接说甲便宜。若乙增长更快、资本回报更高且负债更低，高倍数可能有合理解释。', '按行业标签随意选择可比公司，忽略地区、业务结构、周期位置、租赁和一次性利润造成的会计差异。', '明确可比公司的选择标准，并保证盈利指标与股权价值、经营指标与企业价值相匹配；再用中位数形成估值区间。'],
    ['Margin of Safety — A margin of safety recognizes valuation uncertainty by requiring a gap between estimated value and purchase price.', '安全边际不是“便宜百分之多少”的固定规则，而是为预测误差、周期变化和未知风险留出空间。不确定性越高，所需余量通常越大。', '估值区间为 80—120 元，市场价 95 元。只拿 120 元比较会显得便宜，按保守端则没有边际；决策应说明依赖哪组假设。', '把模型低估当成市场一定会纠正的保证，忽略基本面恶化可能让估值区间本身继续下降。', '记录估值日期、三情景、关键变量和三项失效条件；新信息出现时更新假设，不用股价反向修改结论。'],
  ],
  'macro-economy': [
    ['Gross Domestic Product — GDP measures the market value of final goods and services produced within an economy over a period.', 'GDP 是生产活动的总量尺，不是幸福或财富的完整指标。支出法把它拆为消费、投资、政府购买和净出口，必须区分名义增长与扣除价格后的实际增长。', '消费 70、投资 20、政府 15、出口 10、进口 15，GDP 为 100。进口被减去是为了避免把已包含在消费或投资中的外国生产算作本国生产。', '把 GDP 增长等同于每个人收入同步增长，忽略人口、分配、环境和未计价活动。', '先判断数据是总量还是增速、名义还是实际、同比还是环比年化，再查看四项支出贡献。'],
    ['Inflation — Inflation is a sustained increase in the general price level, not merely a rise in one product’s price.', '通胀要看价格上涨是否广泛、持续并影响预期。它可能由需求过强、供给受限、工资成本或汇率推动，不同来源对应的政策效果不同。', '能源价格一次上涨会直接抬高 CPI，也可能通过运输成本扩散；如果核心服务和工资没有持续加速，总体通胀之后可能回落。', '看到某一商品涨价就称为通胀，或只看同比下降就判断价格正在下降；通胀下降通常只是价格上涨速度变慢。', '拆分食品、能源、商品、住房和服务，比较环比、同比、核心指标与工资，并记录基数影响。'],
    ['Employment and Productivity — Employment reflects labor demand, while productivity determines how much output each unit of labor can produce.', '就业影响家庭收入和周期需求，生产率则决定长期工资与生活水平空间。就业通常滞后：企业先调整工时和招聘，确认需求变化后才大规模增减人员。', '企业用同样 100 名员工把年产量从 1 万件提高到 1.1 万件，劳动生产率提升 10%。如果提升来自临时加班而非技术与流程，未必可持续。', '只看失业率判断劳动力市场，忽略劳动参与率、工时、职位空缺和工资增速。', '同时观察就业人数、失业率、参与率、工时、工资和单位产出，并区分周期恢复与长期效率。'],
    ['Monetary Policy Transmission — Central-bank policy rates affect demand through market rates, credit, asset prices, exchange rates, and expectations.', '央行调整的是金融条件的起点，不是直接命令所有价格。政策经银行贷款、债券收益率、房贷、汇率和预期逐步传到企业与家庭，速度和强度会因经济结构而异。', '政策利率上升后，新房贷成本提高，部分家庭减少购房；企业融资门槛上升，推迟投资。需求降温后，通胀可能滞后数季回落。', '看到加息当天市场上涨就判断政策无效。市场交易的是实际决定相对先前预期的差异，而经济传导需要时间。', '画出至少三条路径，每条写明中介变量、受影响主体和可能时滞，并标注哪些环节可能被抵消。'],
    ['Fiscal Policy — Fiscal policy changes taxes, transfers, and government spending, directly affecting demand and resource allocation.', '财政政策能直接把收入或支出带入经济，但效果取决于资金流向、闲置产能、融资方式和执行速度。赤字是某一时期的流量，政府债务是历年累积的存量。', '经济下行时失业救济自动增加、税收减少，这是自动稳定器；另行批准基建计划属于主动政策，可能因规划与施工产生更长时滞。', '把政府预算类比为家庭预算并认为所有债务都应立即偿还，忽略货币主权、税收能力和宏观周期；反过来也不能认为债务没有约束。', '区分政策规模、实施时点、受益对象、乘数与融资成本，并观察债务利息占财政收入的趋势。'],
    ['Business Cycle — The business cycle describes recurring expansions and contractions driven by demand, credit, investment, inventories, and expectations.', '周期可以帮助描述当前环境，却不能精确标记拐点。库存、信贷、房地产、资本开支和情绪彼此反馈，不同部门还可能处在不同阶段。', '需求突然放缓时，企业先发现库存上升，随后减少订单和生产，供应商收入下降，招聘放缓，最终进一步影响消费。', '根据单一领先指标预测衰退日期，或认为每次周期都必须按固定顺序和时长演变。', '建立增长、通胀、就业、信贷和库存仪表盘，记录方向与变化速度，并保留多个可解释情景。'],
    ['Exchange Rate and Balance of Payments — Exchange rates connect trade, investment returns, capital flows, and monetary conditions across countries.', '汇率是一种货币用另一种货币表示的价格。海外投资的本币回报同时来自资产变化和汇率变化，国际收支则记录经常项目与金融流动。', '美元资产上涨 8%，但美元相对人民币贬值 5%，人民币投资者回报约为 1.08×0.95−1=2.6%，不是简单的 3%。', '看到出口强就断定本币一定升值，忽略资本流动、利差、风险偏好与政策也会同时影响汇率。', '先确认报价方向和投资者本币，再把资产回报与汇率回报相乘；区分贸易现金流和金融账户流动。'],
    ['Expectations and Market Pricing — Markets respond to differences between outcomes and prior expectations, not only to whether news is good or bad.', '财经新闻至少有三层：数据事实、因果解释、市场已计入的预期。好数据也可能伴随下跌，因为结果不够好，或市场担心政策因此收紧。', '市场预期盈利增长 30%，公司实际增长 20%。20% 本身不差，但低于价格已经反映的预期，股价仍可能下跌。', '看到价格反应后倒推唯一原因，忽略同一时间还有估值、仓位和其他信息变化。', '在看市场反应前写下预期值、实际值、前值修订和可能政策含义，再列出至少两个竞争解释。'],
  ],
  'portfolio-management': [
    ['Investment Policy Statement — An IPS documents objectives, constraints, allocation ranges, and decision rules before markets become stressful.', '投资政策书把目标与规则写在情绪之外。它应包含用钱日期、最低安全要求、可承受回撤、资产范围、配置区间和再平衡规则，而不只是收益目标。', '养老账户设长期目标，战略配置股票 60%±5%、债券 30%±5%、现金 10%。当股票升到 67% 时按规则再平衡，不因新闻临时改变边界。', '把 IPS 写成“年收益 10%”的愿望清单，却没有说明能承受多大下跌、何时用钱和偏离后怎样处理。', '用一页纸写目标、期限、现金需求、风险上限、允许资产、配置区间、检查频率与禁止事项。'],
    ['Risk Capacity and Risk Tolerance — Capacity is the financial ability to bear loss; tolerance is the emotional willingness to endure it.', '风险能力由期限、收入、安全垫和责任决定；风险意愿是心理感受。两者冲突时应由更保守的一方约束，否则市场下跌时容易在最坏时点卖出。', '年轻人可能自称很能承受风险，但若两年后需用全部资金买房，客观风险能力仍低。另一个人期限长，却因 10% 下跌失眠，也需降低波动。', '牛市问卷得到高风险分数就永久采用激进配置，忽略意愿会随盈亏变化。', '分别评估目标期限、收入、安全垫和回撤反应；用具体金额而非抽象等级测试自己能否坚持。'],
    ['Diversification and Correlation — Diversification works when holdings respond differently to underlying risk drivers, not merely when they have different names.', '真正分散要看底层驱动。多只基金可能都集中于同一行业；危机时原本相关性低的资产也可能因流动性需求一起下跌。', '持有五只科技主题基金看似数量很多，穿透后前十大股票高度重合。加入不同现金流驱动和期限特征的资产，分散效果才可能改善。', '认为相关系数为零就完全无关。相关性只描述特定区间的线性关系，压力时期会改变，也不包含流动性。', '穿透持仓并按股票、利率、信用、商品、汇率等风险因子归类，再检查正常与压力时期的共同变化。'],
    ['Strategic Asset Allocation — Strategic allocation sets long-term exposure to growth, defensive assets, and liquidity based on goals and risk budget.', '配置先决定承担多少股票、利率、信用等风险，再选具体产品。短期目标需要安全和流动性，长期目标可以换取更高增长暴露。', '一年后学费与二十年后养老不能放在同一风险池。前者可用现金与短债，后者才适合更高股票比例；一个总比例会掩盖期限冲突。', '先挑过去回报最高的基金，再把结果称为资产配置；这实际上是产品堆叠和业绩追逐。', '按目标建立资金桶，写明每桶日期、最低金额和最大损失，再汇总为组合配置区间。'],
    ['Dollar-Cost Averaging — DCA invests fixed amounts over time, reducing timing pressure but not guaranteeing profit or a lower average cost.', '定投适合未来收入逐步到达，也能减轻一次性进入的心理压力。已有一大笔长期资金分批投入，则是在用较少市场暴露换取更平滑体验。', '每月工资拿出 2,000 元投资，本来就只能逐月进入。若已有 20 万闲置，分 12 个月投入会让未投入部分持有现金，市场上涨时可能产生机会成本。', '认为定投一定赚钱或一定比一次投入成本低；持续下跌、产品质量差或期限过短时都不成立。', '区分“未来现金流定投”和“现有现金分批”，写明持续期限、暂停条件及未投入资金的存放方式。'],
    ['Rebalancing — Rebalancing restores portfolio risk by trading back toward target weights on a calendar or threshold rule.', '再平衡的目的不是猜高低，而是恢复风险预算。可以定期检查，也可在偏离超过阈值时行动，同时要考虑税、费用和现金流。', '目标股票 60%，上涨后变成 68%。5 个百分点阈值规则会触发卖出部分股票或用新增资金补足其他资产，使组合回到允许区间。', '频繁把每个小偏离都调回精确目标，产生交易成本与税务；或在下跌时临时取消规则。', '设定检查频率、绝对或相对阈值、资金流优先顺序和税费约束，并保留每次操作记录。'],
    ['Behavioral Bias — Rules and pre-commitments reduce the impact of loss aversion, confirmation bias, and performance chasing.', '行为偏差不是无知，而是人在压力下的系统性倾向。与其要求自己永远理性，更有效的是提前设计冷静期、自动化、核对清单和决策记录。', '投资者看到持仓下跌，只搜索支持“马上反弹”的信息。若规则要求先写出反方证据和原始买入假设，就更容易区分波动与逻辑失效。', '学会偏差名称后认为自己已经免疫。知道“损失厌恶”并不会自动阻止恐慌卖出。', '选自己最常见的一种偏差，为它设计具体触发器、等待时间、反方检查和可执行上限。'],
    ['Performance Attribution — Attribution separates results into market exposure, allocation, security selection, currency, costs, and luck.', '复盘不能只问赚没赚钱。好流程可能短期亏损，坏流程也可能偶然获利；归因要把市场本身、主动决策、汇率和费用分别量化。', '组合收益 8%，基准 7%。其中资产配置贡献 +1.5%，选品贡献 −0.5%，费用 −0.3%，汇率 +0.3%，合计解释相对结果。', '只复盘亏损持仓而不复盘赚钱中的运气，导致错误信心；或频繁更换基准让历史表现看起来更好。', '固定适合目标的基准，按季度拆分市场、配置、选择、汇率和成本，并记录哪些决定可重复。'],
  ],
  'global-finance-risk': [
    ['Financial Intermediation — Financial intermediaries connect savers and borrowers while providing payments, maturity transformation, pricing, and risk transfer.', '银行吸收可随时提取的存款并发放长期贷款，市场则让资金通过证券直接连接。期限转换提高效率，也造成挤兑与流动性风险，因此需要资本、流动性和清算安排。', '银行有大量三十年房贷，却允许存款人随时取款。正常时新存款和流动性储备支持支付；集中提款时，即使贷款最终能收回，也可能短期拿不出现金。', '认为银行只是把存款原封不动借出去，忽略信用创造、资本约束和支付清算体系。', '画出储户、银行、借款人和央行的资产负债关系，区分偿付能力不足与短期流动性不足。'],
    ['Yield Curve — A yield curve plots interest rates across maturities and reflects expected short rates, inflation, and term premia.', '收益率曲线不是单一预测器。短端受当前政策影响更直接，长端综合未来短率预期、通胀与期限溢价；倒挂可能反映预期降息，也可能包含风险偏好变化。', '两年期收益率 4.5%、十年期 3.8% 形成倒挂。市场可能预期经济放缓后降息，但倒挂本身不能给出衰退的精确日期。', '把长端利率简单当作未来短端平均值，忽略期限溢价会随供需、风险与央行资产负债表变化。', '比较不同日期的整条曲线，拆分水平、斜率和曲率，并结合通胀预期和期限溢价解释。'],
    ['Currency Hedging — Currency hedging offsets exchange-rate exposure but introduces cost, basis, liquidity, and implementation choices.', '海外资产有资产风险和货币风险两层。是否对冲取决于未来支出货币、资产类型、期限和对冲成本；对冲降低一种波动，也可能失去有利汇率变化。', '一年后需支付 10 万美元学费，持有美元现金形成自然对冲；若资金放在高波动美元股票中，虽然币种匹配，资产价格仍可能下跌。', '把“海外资产用外币计价”视为已经分散，忽略本币升值可能抵消资产收益，也忽略企业收入本身的全球币种敞口。', '先定义未来负债币种，再分开计算资产与汇率敞口；核对远期点、滚动频率、保证金和税务。'],
    ['Commodity Futures — Commodity-futures returns depend on spot-price changes, collateral yield, and the roll yield from the futures curve.', '商品期货不等于仓库存着现货。合约到期需要换月，远月比近月贵时滚动会产生损耗，反向结构则可能贡献收益，此外还有保证金与抵押资金收益。', '油价现货一年不变，但基金每月卖出较便宜的近月、买入更贵的远月，连续负滚动收益仍可能让净值下降。', '看到新闻说原油涨 20%，就预期所有原油期货基金也涨 20%，忽略期限结构、换月规则和费用。', '写出所持工具是现货、生产商股票还是期货；查看曲线结构、换月日、保证金和历史跟踪差异。'],
    ['Futures and Options — Futures create bilateral obligations, while options give the buyer a right and impose an obligation on the seller.', '期货双方都承担到期或平仓义务，保证金只是履约担保；期权买方支付权利金获得选择权，卖方收取权利金并承担被行权义务。', '买入执行价 100 的看涨期权，权利金 5。到期价格 120 时毛收益 20、净收益 15；价格低于 100 可放弃，最大损失为 5。卖方损益方向相反。', '把卖期权收到的权利金当成稳定利息，忽略小概率大损失和追加保证金；或把保证金误认为最大损失。', '画出到期损益图，标明权利、义务、盈亏平衡、最大损失、保证金与提前平仓条件。'],
    ['Leverage and Liquidity Spiral — Falling prices can trigger margin calls and forced selling, which causes further price declines.', '杠杆把小额自有资金控制更大头寸。价格下跌后抵押品缩水，交易者需补现金或卖出；多人同时卖出会压低价格并让更多账户触发限制。', '100 万自有资金控制 500 万资产，资产下跌 10% 就损失 50 万，自有资金减少一半。若贷款方提高保证金要求，即使看好长期价值也可能被迫卖出。', '只用平均波动估算杠杆安全边界，忽略跳空、相关性上升、融资方改变条件和市场深度消失。', '计算名义敞口、初始与维持保证金、10%—30% 跳空损失和补资时间，并预留独立流动性。'],
    ['Financial Regulation — Regulation sets rules for conduct, disclosure, capital, custody, and resolution, but does not guarantee investment returns.', '监管解决的是制度与行为边界：谁能经营、客户资产如何隔离、信息怎样披露、机构失败后怎样处置。合规只说明满足某些规则，不代表产品保本或价格不会下跌。', '受监管券商可以合法提供股票交易，客户仍会承担股票价格风险；若客户资产按规定隔离，券商破产时的处置风险与投资亏损是不同问题。', '看到牌照就停止尽调，或把备案、会员资格和监管许可混为一谈。', '在监管机构官网核验主体与许可范围，检查托管、客户资金隔离、投诉渠道和风险揭示，不依赖平台截图。'],
    ['Fintech and Digital Assets — Technology can improve financial processes but does not remove custody, liquidity, governance, model, or economic risk.', '新技术能降低转账和自动化成本，却不能取消谁控制资产、收益从哪里来、错误如何纠正这些基本问题。数字资产还叠加私钥、智能合约和平台治理风险。', '某平台提供 10% 稳定币收益，需要追问借款人是谁、抵押品是什么、清算如何执行以及平台破产时客户排位；界面顺畅不等于现金流可靠。', '把区块链可查等同于资产安全。链上记录可能透明，但私钥丢失、合约漏洞、预言机和中心化托管仍会造成损失。', '核对法律主体、资产控制权、代码审计、抵押与清算、流动性、治理权限、收益来源和退出路径。'],
  ],
};

export function buildLessonGuide(course: Course, lesson: CourseLesson): LessonGuide {
  const note = lessonNotes[course.slug]?.[lesson.id - 1];
  const [english, intuition, example, pitfall, exerciseHint] = note ?? [
    `${lesson.title} — ${lesson.summary}`,
    lesson.summary,
    `可依据“${lesson.key}”建立数值例子，并比较关键假设变化前后的结果。`,
    '忽略模型假设、交易成本、税收与现金流时点，会使理论结果偏离现实。',
    '列出已知变量、假设与计算过程，并说明结论的适用条件。',
  ];

  return {
    english,
    plain: lesson.summary,
    why: intuition,
    example,
    misconceptions: [pitfall],
    exerciseHint,
  };
}
